library(foreign)
library(corpcor)
library(tseries)
library(quantmod)
library(plyr)
library(dplyr)
library(DMwR)
library(Hmisc)

data<-read.xport("F:/wifeintern/DEMO_I.XPT")
data_food2<-read.xport("F:/wifeintern/DR2IFF_I.XPT")
data_food3<-read.xport("F:/wifeintern/DR1TOT_I.XPT")
data_food4<-read.xport("F:/wifeintern/DR2TOT_I.XPT")
data_food1<-read.xport("F:/wifeintern/DR2IFF_I.XPT")



data_question1 <-read.xport("F:/wifeintern/ACQ_I.XPT")

#questionnaire_1 = left_join(food_1, data_question1, by = "SEQN")
#rm(data_question1)
#rm(food_1)
#gc()

data_question2 <-read.xport("F:/wifeintern/ALQ_I.XPT")

#questionnaire_1 = left_join(questionnaire_1, data_question2, by = "SEQN")
#rm(data_question2)
#gc()

questionnaire_1 = left_join(data_question1, data_question2, by = "SEQN")
rm(data_question1)
rm(data_question2)
gc()

questionnaire_1 = left_join(data_question1, data_food1, by = "SEQN")
questionnaire_1 = left_join(data_question1, data_food2, by = "SEQN")
questionnaire_1 = left_join(data_question1, data_food3, by = "SEQN")
questionnaire_1 = left_join(data_question1, data_food4, by = "SEQN")
questionnaire_1 = left_join(data_question1, data, by = "SEQN")




# food_1 = left_join(data_food2, data_food3, by="SEQN")
# food_1 =left_join(food_1, data_food4, by = "SEQN")
# food_1 = left_join(food_1, data, by = "SEQN")
# food_1 = left_join(food_1, data_food1, by = "SEQN")

rm(data_food2)
rm(data_food3)
rm(data_food4)
rm(data)
rm(data_food1)
gc()

#questionnaire_1 = left_join(questionnaire_1, food_1, by = "SEQN")
#rm(food_1)
gc()

data_question3 <-read.xport("F:/wifeintern/AUQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question3, by = "SEQN")
rm(data_question3)
gc()
data_question4 <-read.xport("F:/wifeintern/BPQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question4, by = "SEQN")
rm(data_question4)
gc()
data_question5 <-read.xport("F:/wifeintern/CBQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question5, by = "SEQN")
rm(data_question5)
gc()
data_question6 <-read.xport("F:/wifeintern/CDQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question6, by = "SEQN")
rm(data_question6)
gc()
data_question7 <-read.xport("F:/wifeintern/DBQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question7, by = "SEQN")
rm(data_question7)
gc()
data_question8 <-read.xport("F:/wifeintern/DEQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question8, by = "SEQN")
rm(data_question8)
gc()
data_question9 <-read.xport("F:/wifeintern/DIQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question9, by = "SEQN")
rm(data_question9)
gc()
data_question10 <-read.xport("F:/wifeintern/DlQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question10, by = "SEQN")
rm(data_question10)
gc()
dpq <-read.xport("F:/wifeintern/DPQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, dpq, by = "SEQN")
gc()
data_question12 <-read.xport("F:/wifeintern/DUQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question12, by = "SEQN")
rm(data_question12)
gc()
data_question13 <-read.xport("F:/wifeintern/ECQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question13, by = "SEQN")
rm(data_question13)
gc()
data_question14 <-read.xport("F:/wifeintern/HEQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question14, by = "SEQN")
rm(data_question14)
gc()
data_question15 <-read.xport("F:/wifeintern/HIQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question15, by = "SEQN")
rm(data_question15)
gc()
data_question16 <-read.xport("F:/wifeintern/HOQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question16, by = "SEQN")
rm(data_question16)
gc()
data_question17 <-read.xport("F:/wifeintern/HSQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question17, by = "SEQN")
rm(data_question17)
gc()
data_question18 <-read.xport("F:/wifeintern/HUQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question18, by = "SEQN")
rm(data_question18)
gc()
data_question19 <-read.xport("F:/wifeintern/IMQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question19, by = "SEQN")
rm(data_question19)
gc()
data_question20 <-read.xport("F:/wifeintern/INQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question20, by = "SEQN")
rm(data_question20)
gc()
data_question21 <-read.xport("F:/wifeintern/KIQ_U_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question21, by = "SEQN")
rm(data_question21)
gc()
data_question22 <-read.xport("F:/wifeintern/MCQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question22, by = "SEQN")
rm(data_question22)
gc()
data_question23 <-read.xport("F:/wifeintern/OCQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question23, by = "SEQN")
rm(data_question23)
gc()
data_question24 <-read.xport("F:/wifeintern/OHQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question24, by = "SEQN")
rm(data_question24)
gc()
data_question25 <-read.xport("F:/wifeintern/PAQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question25, by = "SEQN")
rm(data_question25)
gc()
data_question26 <-read.xport("F:/wifeintern/PFQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question26, by = "SEQN")
rm(data_question26)
gc()
data_question27 <-read.xport("F:/wifeintern/RHQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question27, by = "SEQN")
rm(data_question27)
gc()
data_question28 <-read.xport("F:/wifeintern/MCQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question28, by = "SEQN")
rm(data_question28)
gc()
data_question29 <-read.xport("F:/wifeintern/OCQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question29, by = "SEQN")
rm(data_question29)
gc()
data_question30 <-read.xport("F:/wifeintern/OHQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question30, by = "SEQN")
rm(data_question30)
gc()
data_question31 <-read.xport("F:/wifeintern/PAQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question31, by = "SEQN")
rm(data_question31)
gc()
data_question32 <-read.xport("F:/wifeintern/PFQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question32, by = "SEQN")
rm(data_question32)
gc()
data_question33 <-read.xport("F:/wifeintern/RHQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question33, by = "SEQN")
rm(data_question33)
gc()
# data_question34 <-read.xport("F:/wifeintern/RXQ_DRUG.XPT")
# questionnaire_1 = left_join(questionnaire_1, data_question34, by = "SEQN")
# rm(data_question34)
# gc()
# data_question35 <-read.xport("F:/wifeintern/RXQ_RX_I.XPT")
# questionnaire_1 = left_join(questionnaire_1, data_question35, by = "SEQN")
# rm(data_question35)
# gc()
# data_question36 <-read.xport("F:/wifeintern/RXQASA_I.XPT")
# questionnaire_1 = left_join(questionnaire_1, data_question36, by = "SEQN")
# rm(data_question36)
# gc()
# data_question37 <-read.xport("F:/wifeintern/SLQ_I.XPT")
# questionnaire_1 = left_join(questionnaire_1, data_question37, by = "SEQN")
# rm(data_question37)
# gc()
# data_question38 <-read.xport("F:/wifeintern/SMQ_I.XPT")
# questionnaire_1 = left_join(questionnaire_1, data_question38, by = "SEQN")
# rm(data_question38)
# gc()
data_question39 <-read.xport("F:/wifeintern/SMQFAM_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question39, by = "SEQN")
rm(data_question39)
gc()
data_question40 <-read.xport("F:/wifeintern/SMQRTU_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question40, by = "SEQN")
rm(data_question40)
gc()
data_question41 <-read.xport("F:/wifeintern/SMQSHS_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question41, by = "SEQN")
rm(data_question41)
gc()
data_question42 <-read.xport("F:/wifeintern/SXQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question42, by = "SEQN")
rm(data_question42)
gc()
data_question43 <-read.xport("F:/wifeintern/VTQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question43, by = "SEQN")
rm(data_question43)
gc()
data_question44 <-read.xport("F:/wifeintern/WHQ_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question44, by = "SEQN")
rm(data_question44)
gc()
data_question45 <-read.xport("F:/wifeintern/WHQMEC_I.XPT")
questionnaire_1 = left_join(questionnaire_1, data_question45, by = "SEQN")
rm(data_question45)
gc()


all = questionnaire_1
all[is.na(all)] <- 0
newAll <- all
gc()
newAll = centralImputation(newAll)
gc()
cov = cov(newAll, method = "spearman")
gc()
cor = cor(newAll, method = "spearman")
gc()
p = cor2pcor(cov)
gc()

